---
- name: Pull image and run container
  community.docker.docker_container:
    name: '{{ docker_container_name }}'
    image: "{{ docker_image }}:{{ docker_tag }}"
    exposed_ports:
      - 7098
    published_ports:
      - 7098:7098
    platform: linux/amd64
  tags:
    - deployment
  block:
    - name: Create directory for volume
      file:
        path: "{{ volume_path }}"
        state: directory
        mode: 0755

    - name: Copy volume file
      template:
        src: "{{ volume_file_name }}.j2"
        dest: "{{ volume_file_path }}"
        mode: 0777